// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gachaAPI.Models;

public partial class GachaMachine
{
    public int Id { get; set; }

    public int ThemeId { get; set; }

    public string MachineName { get; set; }

    public string MachineDescription { get; set; }

    public string MachinePictureName { get; set; }

    public DateTime? CreateTime { get; set; }

    public int Price { get; set; }

    public bool Status { get; set; }

    public virtual ICollection<GachaProduct> GachaProducts { get; set; } = new List<GachaProduct>();

    public virtual GachaTheme Theme { get; set; }

    public virtual ICollection<TrackingList> TrackingLists { get; set; } = new List<TrackingList>();
}