// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gachaAPI.Models;

public partial class GachaProduct
{
    public int Id { get; set; }

    public int MachineId { get; set; }

    public string ProductName { get; set; }

    public int Stock { get; set; }

    public string ProductPictureName { get; set; }

    public DateTime? CreateTime { get; set; }

    public virtual ICollection<Bag> Bags { get; set; } = new List<Bag>();

    public virtual ICollection<ExchangeRecord> ExchangeRecordGachaIdFromNavigations { get; set; } = new List<ExchangeRecord>();

    public virtual ICollection<ExchangeRecord> ExchangeRecordGachaIdToNavigations { get; set; } = new List<ExchangeRecord>();

    public virtual GachaMachine Machine { get; set; }
}