// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gachaAPI.Models;

public partial class Permission
{
    public int Id { get; set; }

    public string PermissionDesc { get; set; }

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}