// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gachaAPI.Models;

public partial class Shipping
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public DateTime? ShippingDate { get; set; }

    public string ShippingStatus { get; set; }

    public string ShippingAddress { get; set; }

    public string ContactPhone { get; set; }

    public string ShippingMethod { get; set; }

    public int ShippingFee { get; set; }

    public virtual ICollection<ShippingDetail> ShippingDetails { get; set; } = new List<ShippingDetail>();

    public virtual UserInfo User { get; set; }
}