// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gachaAPI.Models;

public partial class ShippingDetail
{
    public int Id { get; set; }

    public int ShippingId { get; set; }

    public int BagId { get; set; }

    public int Quantity { get; set; }

    public virtual Bag Bag { get; set; }

    public virtual ICollection<ConvenienceStoreInfo> ConvenienceStoreInfos { get; set; } = new List<ConvenienceStoreInfo>();

    public virtual Shipping Shipping { get; set; }
}