// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gachaAPI.Models;

public partial class TrackingList
{
    public int UserId { get; set; }

    public int GachaMachineId { get; set; }

    public DateTime? TrackingDate { get; set; }

    public string NoteStatus { get; set; }

    public virtual GachaMachine GachaMachine { get; set; }

    public virtual UserInfo User { get; set; }
}