// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace szAPI.Models;

public partial class Admin
{
    public int Id { get; set; }

    public string Account { get; set; }

    public int RoleId { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Password { get; set; }

    public virtual Role Role { get; set; }
}