// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace szAPI.Models;

public partial class Announcement
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string Image { get; set; }

    public DateTime? CreatedAt { get; set; }
}