// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace szAPI.Models;

public partial class GachaDetailList
{
    public int Id { get; set; }

    public int BagId { get; set; }

    public int ExchangeRecordId { get; set; }

    public int UploadRecordId { get; set; }

    public virtual Bag Bag { get; set; }

    public virtual ExchangeRecord ExchangeRecord { get; set; }

    public virtual UploadRecord UploadRecord { get; set; }
}