// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace szAPI.Models;

public partial class Message
{
    public int Id { get; set; }

    public int ChatRoomId { get; set; }

    public int SenderId { get; set; }

    public string Content { get; set; }

    public DateTime? SendDate { get; set; }

    public virtual ChatRoom ChatRoom { get; set; }

    public virtual UserInfo Sender { get; set; }
}