// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class achievement
{
    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public string achievementType { get; set; }

    public int target { get; set; }

    public DateTime? createdAt { get; set; }

    public virtual ICollection<achievementProgress> achievementProgress { get; set; } = new List<achievementProgress>();

    public virtual ICollection<pointList> pointList { get; set; } = new List<pointList>();

    public virtual ICollection<userAchievement> userAchievement { get; set; } = new List<userAchievement>();
}