// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class AchievementProgress
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int AchievementId { get; set; }

    public int Progress { get; set; }

    public int Target { get; set; }

    public virtual Achievement Achievement { get; set; }

    public virtual UserInfo User { get; set; }
}