// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class achievementProgress
{
    public int id { get; set; }

    public int userID { get; set; }

    public int achievementID { get; set; }

    public int progress { get; set; }

    public int target { get; set; }

    public virtual achievement achievement { get; set; }

    public virtual userInfo user { get; set; }
}