// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class activity
{
    public int id { get; set; }

    public string title { get; set; }

    public string description { get; set; }

    public bool status { get; set; }

    public int activityTypeId { get; set; }

    public DateTime? createdAt { get; set; }

    public DateTime? activityStart { get; set; }

    public DateTime? activityEnd { get; set; }

    public virtual ICollection<activityLinkVoucher> activityLinkVoucher { get; set; } = new List<activityLinkVoucher>();

    public virtual activityType activityType { get; set; }
}