// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class activityType
{
    public int id { get; set; }

    public string name { get; set; }

    public DateTime? createdAt { get; set; }

    public bool status { get; set; }

    public virtual ICollection<activity> activity { get; set; } = new List<activity>();
}