// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class announcement
{
    public int id { get; set; }

    public string title { get; set; }

    public string content { get; set; }

    public string image { get; set; }

    public DateTime? createdAt { get; set; }
}