// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class chatRoom
{
    public int id { get; set; }

    public int user1ID { get; set; }

    public int user2ID { get; set; }

    public DateTime? createdAt { get; set; }

    public virtual ICollection<message> message { get; set; } = new List<message>();

    public virtual userInfo user1 { get; set; }

    public virtual userInfo user2 { get; set; }
}