// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class ConvenienceStoreInfo
{
    public int Id { get; set; }

    public int StoreId { get; set; }

    public int UserId { get; set; }

    public int ShippingDetailId { get; set; }

    public virtual ShippingDetail ShippingDetail { get; set; }

    public virtual ConvenienceStore Store { get; set; }

    public virtual UserInfo User { get; set; }
}