// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class convenienceStoreInfo
{
    public int Id { get; set; }

    public int storeId { get; set; }

    public int userId { get; set; }

    public int shippingDetailId { get; set; }

    public virtual shippingDetail shippingDetail { get; set; }

    public virtual convenienceStore store { get; set; }

    public virtual userInfo user { get; set; }
}