// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class exchangeRecord
{
    public int id { get; set; }

    public int? userIdFrom { get; set; }

    public int? userIdTo { get; set; }

    public int? gachaIdFrom { get; set; }

    public int? gachaIdTo { get; set; }

    public DateTime? exchangeDate { get; set; }

    public virtual ICollection<gachaDetailList> gachaDetailList { get; set; } = new List<gachaDetailList>();

    public virtual gachaProduct gachaIdFromNavigation { get; set; }

    public virtual gachaProduct gachaIdToNavigation { get; set; }

    public virtual userInfo userIdFromNavigation { get; set; }

    public virtual userInfo userIdToNavigation { get; set; }
}