// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class gachaMachine
{
    public int id { get; set; }

    public int themeId { get; set; }

    public string machineName { get; set; }

    public string machineDescription { get; set; }

    public string machinePictureName { get; set; }

    public DateTime? createTime { get; set; }

    public int price { get; set; }

    public virtual ICollection<gachaProduct> gachaProduct { get; set; } = new List<gachaProduct>();

    public virtual gachaTheme theme { get; set; }

    public virtual ICollection<trackingList> trackingList { get; set; } = new List<trackingList>();
}