// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class gachaTheme
{
    public int id { get; set; }

    public string themeName { get; set; }

    public virtual ICollection<gachaMachine> gachaMachine { get; set; } = new List<gachaMachine>();
}