// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class gachaProduct
{
    public int id { get; set; }

    public int machineId { get; set; }

    public string productName { get; set; }

    public int stock { get; set; }

    public string productPictureName { get; set; }

    public DateTime? createTime { get; set; }

    public virtual ICollection<bag> bag { get; set; } = new List<bag>();

    public virtual ICollection<exchangeRecord> exchangeRecordgachaIdFromNavigation { get; set; } = new List<exchangeRecord>();

    public virtual ICollection<exchangeRecord> exchangeRecordgachaIdToNavigation { get; set; } = new List<exchangeRecord>();

    public virtual gachaMachine machine { get; set; }

    public virtual ICollection<uploadRecord> uploadRecord { get; set; } = new List<uploadRecord>();
}