// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class message
{
    public int id { get; set; }

    public int chatRoomID { get; set; }

    public int senderID { get; set; }

    public string content { get; set; }

    public DateTime? sendDate { get; set; }

    public virtual chatRoom chatRoom { get; set; }

    public virtual userInfo sender { get; set; }
}