// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class pointList
{
    public int id { get; set; }

    public string? rechargeListId { get; set; }

    public int? bagId { get; set; }

    public int? achievementId { get; set; }

    public int? changedPoint { get; set; }

    public virtual achievement achievement { get; set; }

    public virtual bag bag { get; set; }

    public virtual rechargeList rechargeList { get; set; }
}