// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class rechargePlan
{
    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public int point { get; set; }

    public int price { get; set; }

    public bool status { get; set; }

    public DateTime? createdAt { get; set; }

    public DateTime? updatedAt { get; set; }

    public virtual ICollection<rechargeList> rechargeList { get; set; } = new List<rechargeList>();
}