// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models
{
    public class rolePermission
    {
        public int roleId { get; set; }
        public int permissionId { get; set; }
    }
}
