// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class role
{
    public int id { get; set; }

    public string title { get; set; }

    public virtual ICollection<admin> admin { get; set; } = new List<admin>();

    public virtual ICollection<permission> permission { get; set; } = new List<permission>();
}