// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class shippingDetail
{
    public int id { get; set; }

    public int shippingId { get; set; }

    public int bagId { get; set; }

    public int quantity { get; set; }

    public virtual bag bag { get; set; }

    public virtual ICollection<convenienceStoreInfo> convenienceStoreInfo { get; set; } = new List<convenienceStoreInfo>();

    public virtual shipping shipping { get; set; }
}