// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class shipping
{
    public int id { get; set; }

    public int userId { get; set; }

    public DateTime? shippingDate { get; set; }

    public string shippingStatus { get; set; }

    public string shippingAddress { get; set; }

    public string contactPhone { get; set; }

    public string shippingMethod { get; set; }

    public int shippingFee { get; set; }

    public virtual ICollection<shippingDetail> shippingDetail { get; set; } = new List<shippingDetail>();

    public virtual userInfo user { get; set; }
}