// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class uploadRecord
{
    public int id { get; set; }

    public int bagId { get; set; }

    public int wantProductId { get; set; }

    public DateTime? uploadDate { get; set; }

    public virtual bag bag { get; set; }

    public virtual ICollection<gachaDetailList> gachaDetailList { get; set; } = new List<gachaDetailList>();

    public virtual gachaProduct wantProduct { get; set; }
}