// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class UserPassword
{
    public string Email { get; set; }

    public string UserPassword1 { get; set; }
}