// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class userVoucher
{
    public int id { get; set; }

    public int userId { get; set; }

    public int voucherID { get; set; }

    public int quantity { get; set; }

    public DateTime startDate { get; set; }

    public DateTime endDate { get; set; }

    public virtual userInfo user { get; set; }

    public virtual voucher voucher { get; set; }
}