// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class userPassword
{
    public string email { get; set; }

    public string userPassword1 { get; set; }
}