// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class userInfo
{
    public int id { get; set; }

    public string userName { get; set; }

    public string phoneNumber { get; set; }

    public string email { get; set; }

    public string address { get; set; }

    public string gender { get; set; }

    public bool? emailConfirm { get; set; }

    public string emailToken { get; set; }

    public int points { get; set; }

    public virtual ICollection<achievementProgress> achievementProgress { get; set; } = new List<achievementProgress>();

    public virtual ICollection<bag> bag { get; set; } = new List<bag>();

    public virtual ICollection<chatRoom> chatRoomuser1 { get; set; } = new List<chatRoom>();

    public virtual ICollection<chatRoom> chatRoomuser2 { get; set; } = new List<chatRoom>();

    public virtual ICollection<checkIn> checkIn { get; set; } = new List<checkIn>();

    public virtual ICollection<convenienceStoreInfo> convenienceStoreInfo { get; set; } = new List<convenienceStoreInfo>();

    public virtual ICollection<exchangeRecord> exchangeRecorduserIdFromNavigation { get; set; } = new List<exchangeRecord>();

    public virtual ICollection<exchangeRecord> exchangeRecorduserIdToNavigation { get; set; } = new List<exchangeRecord>();

    public virtual ICollection<message> message { get; set; } = new List<message>();

    public virtual ICollection<rechargeList> rechargeList { get; set; } = new List<rechargeList>();

    public virtual ICollection<shipping> shipping { get; set; } = new List<shipping>();

    public virtual ICollection<trackingList> trackingList { get; set; } = new List<trackingList>();

    public virtual ICollection<userAchievement> userAchievement { get; set; } = new List<userAchievement>();

    public virtual ICollection<userVoucher> userVoucher { get; set; } = new List<userVoucher>();
}