// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gacha.Models;

public partial class voucher
{
    public int id { get; set; }

    public string voucherName { get; set; }

    public string voucherCode { get; set; }

    public string voucherDescription { get; set; }

    public int duration { get; set; }

    public virtual ICollection<activityLinkVoucher> activityLinkVoucher { get; set; } = new List<activityLinkVoucher>();

    public virtual ICollection<userVoucher> userVoucher { get; set; } = new List<userVoucher>();
}